# SITE SETTINGS
baseurl: /alcatraz
exclude: ['README.md']
markdown: kramdown
timezone: UTC
future: true

# LANGUAGES
l:
  en: English
  nl: Nederlands
  fr: Fran√ßais

langs:
  - "en"
  - "fr"
  - "nl"

# PRICES
p:
  friday: '55'
  saturday: '70'
  sunday: '70'
  combi: '140'
  friday-vip: '100'
  saturday-vip: '130,5'
  sunday-vip: '130,5'
  combi-vip: '255'
  combi-vip-xl: '500'
  camping: '16'
  camping-motor: '25'
  camping-camper: '50'
  camping-diy: '115'
  camping-tipi: '180'
  camping-bell-2: '250'
  camping-bell-4: '500'

# COLLECTIONS
collections:
  bands:
    output: true
  info:
    output: true
  pages:
    output: true

permalinks: pretty

defaults:
  -
    scope:
      path: "_bands/en"
    values:
      permalink: "/en/bands/:title"
      lang: "en"
  -
    scope:
      path: "_bands/nl"
    values:
      permalink: "/nl/bands/:title"
      lang: "nl"
  -
    scope:
      path: "_bands/fr"
    values:
      permalink: "/fr/bands/:title"
      lang: "fr"
  -
    scope:
      path: "_info/en"
    values:
      permalink: "/en/info/:title"
      lang: "en"
  -
    scope:
      path: "_info/nl"
    values:
      permalink: "/nl/info/:title"
      lang: "nl"
  -
    scope:
      path: "_info/fr"
    values:
      permalink: "/fr/info/:title"
      lang: "fr"
  -
    scope:
      path: "_pages/en"
    values:
      permalink: "/en/:title"
      lang: "en"
  -
    scope:
      path: "_pages/nl"
    values:
      permalink: "/nl/:title"
      lang: "nl"
  -
    scope:
      path: "_pages/fr"
    values:
      permalink: "/fr/:title"
      lang: "fr"
